export const ptBr = {
  pendingBalance: 'Saldo a receber',
  estimatedEarning: 'Ganho estimado',
  copy: 'Copiar',
  copySuccess: 'Carteira copiada para a área de transferência.',
  current: 'Atual',
  average: 'Média',
  reported: 'Reportado',
  day: 'dia',
  week: 'semana',
  mounth: 'mês',
  valid: 'Válido',
  stale: 'Atrasado',
  invalid: 'Inválido',
  pendingShares: 'Shares pendentes',
  roundParticipation: 'Participação no round',
  approximateReward: 'Recompensa aproximada',
  lastSubmittedShare: 'Último share submetido',
}
